name: build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Move to flask folder
        run: |
          cd app
      - name: Run test suite
        run: |
          pipenv run pytest
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Run black formatter
        uses: rickstaa/action-black@v1.3.1

  test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Move to flask folder
        run: |
          cd app
      - name: Report coverage
        run: |
          pipenv run pytest --cov=app
  
  coverage-commentator:
    runs-on: ubuntu-latest
    steps:
      - name: pytest-coverage-commentator
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
            